{{- if .Values.monitoringPortForward.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-port-forward
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ .Values.monitoringPortForward.grafanaSecretName | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-port-forward
subjects:
  - kind: Group
    name: {{ .Values.monitoringPortForward.groupName | quote }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: monitoring-port-forward
  apiGroup: rbac.authorization.k8s.io
{{- end }}
