backend:
  replicaCount: 2
  image:
    tag: latest
    digest: ""
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60

worker:
  replicaCount: 1
  image:
    tag: latest
    digest: ""
  autoscaling:
    keda:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      pollingIntervalSeconds: 15
      cooldownPeriodSeconds: 180
      queue:
        listName: default
        targetLength: 5
        activationLength: 1
        databaseIndex: 0
        enableTLS: true

frontendAdmin:
  image:
    tag: latest
    digest: ""

nginx:
  replicaCount: 2
  image:
    tag: latest
    digest: ""