backend:
  replicaCount: 1
  image:
    tag: 257f59797f69e38f7e18026a8d50b81865b6d59c
    digest: ""
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 40
worker:
  replicaCount: 1
  image:
    tag: 257f59797f69e38f7e18026a8d50b81865b6d59c
    digest: ""
  autoscaling:
    keda:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      pollingIntervalSeconds: 15
      cooldownPeriodSeconds: 120
      queue:
        targetLength: 2
        activationLength: 1
        enableTLS: true
frontendAdmin:
  image:
    tag: 257f59797f69e38f7e18026a8d50b81865b6d59c
    digest: ""
nginx:
  replicaCount: 1
  image:
    tag: 257f59797f69e38f7e18026a8d50b81865b6d59c
    digest: ""
