backend:
  replicaCount: 1
  image:
    tag: latest
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 40

worker:
  replicaCount: 1
  image:
    tag: latest
  autoscaling:
    keda:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      pollingIntervalSeconds: 15
      cooldownPeriodSeconds: 120
      queue:
        targetLength: 2
        activationLength: 1
        enableTLS: true

frontendAdmin:
  image:
    tag: latest

nginx:
  replicaCount: 1