envSecretName: face-detector-env
imagePullSecrets: []

backend:
  replicaCount: 1
  image:
    repository: ""
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: backend
    port: 8000
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

worker:
  enabled: true
  replicaCount: 1
  image:
    repository: ""
    tag: latest
    pullPolicy: IfNotPresent
  command:
    - celery
    - -A
    - app.worker.celery_app.celery_app
    - worker
    - --loglevel=info
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  autoscaling:
    keda:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      pollingIntervalSeconds: 30
      cooldownPeriodSeconds: 300
      queue:
        listName: default
        targetLength: 5
        activationLength: 1
        databaseIndex: 0
        enableTLS: false
        addressEnvName: REDIS_ADDRESS
        usernameEnvName: ""
        passwordEnvName: REDIS_PASSWORD

frontendAdmin:
  replicaCount: 1
  image:
    repository: ""
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: frontend-admin
    port: 80

nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: 1.27-alpine
    pullPolicy: IfNotPresent
  service:
    name: nginx
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
