{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app.kubernetes.io/name: face-detector
    app.kubernetes.io/component: worker
spec:
{{- if not .Values.worker.autoscaling.keda.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: face-detector
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: face-detector
        app.kubernetes.io/component: worker
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: "{{ include "face-detector.imageRef" .Values.worker.image }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          command:
{{ toYaml .Values.worker.command | indent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecretName }}
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
{{- end }}
